# Generated by Django 3.2.6 on 2021-08-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Температура объекта', 'verbose_name_plural': 'Температура объектов'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Объект измерения', 'verbose_name_plural': 'Объекты измерения'},
        ),
    ]