# Generated by Django 3.2.7 on 2021-09-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20210818_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.project'),
        ),
    ]